"""Team resolution (which project dir / which role am I), role names and tmux helpers."""
from __future__ import annotations

import contextlib
import os
import re
import shutil
import subprocess
from pathlib import Path
from typing import Iterator, Mapping

from . import store

ROLE_RE = re.compile(r"^[A-Za-z0-9_]+$")
SYSTEM = "hermes-crew"           # sender name of messages generated by the tool itself
RESERVED = ("lead", "user", SYSTEM)


def valid_role(name: str) -> bool:
    return bool(name) and bool(ROLE_RE.match(name))


def same_role(a: str | None, b: str | None) -> bool:
    return a is not None and b is not None and a.lower() == b.lower()


def is_lead(role: str | None) -> bool:
    """`lead`, or `user` (a human at a plain shell) — both may override teammates."""
    return (role or "").lower() in ("lead", "user")


# ---------------------------------------------------------------- tmux
def tmux(*args: str, timeout: float = 3.0) -> str | None:
    """Run tmux; stdout without trailing newline, or None if tmux is missing / fails / times out."""
    if not shutil.which("tmux"):
        return None
    try:
        p = subprocess.run(["tmux", *args], capture_output=True, text=True, timeout=timeout)
    except (OSError, subprocess.SubprocessError):
        return None
    if p.returncode != 0:
        return None
    return p.stdout.rstrip("\n")


def _ppid(pid: int) -> int:
    try:
        stat = Path(f"/proc/{pid}/stat").read_text()
        return int(stat.rsplit(")", 1)[1].split()[1])
    except (OSError, ValueError, IndexError):
        return 0


def my_pane(pid: int | None = None) -> str | None:
    """The tmux pane whose process is an ancestor of `pid` (default: this process).

    Same idea as bash `my_pane()`: works even when $TMUX is unset (e.g. Hermes' terminal tool).
    Falls back to $TMUX_PANE if the walk finds nothing.
    """
    out = tmux("list-panes", "-a", "-F", "#{pane_pid} #{pane_id}")
    if out:
        panes = {}
        for line in out.splitlines():
            parts = line.split()
            if len(parts) == 2 and parts[0].isdigit():
                panes[int(parts[0])] = parts[1]
        p = pid or os.getpid()
        seen = set()
        while p > 1 and p not in seen:
            seen.add(p)
            if p in panes:
                return panes[p]
            p = _ppid(p)
        env_pane = os.environ.get("TMUX_PANE")
        if env_pane and env_pane in panes.values():
            return env_pane
    return None


def pane_option(pane: str, name: str) -> str | None:
    v = tmux("display", "-p", "-t", pane, f"#{{{name}}}")
    return v or None


def window_option(target: str, name: str) -> str | None:
    v = tmux("show", "-wv", "-t", target, name)
    return v or None


# ---------------------------------------------------------------- identity
def current_role(env: Mapping[str, str] | None = None, pane: str | None = None) -> str:
    """$HERMES_TEAM_ROLE -> tmux @role of my pane -> "user"."""
    env = os.environ if env is None else env
    role = (env.get("HERMES_TEAM_ROLE") or "").strip()
    if role:
        return role
    pane = pane or my_pane()
    if pane:
        r = pane_option(pane, "@role")
        if r:
            return r
    return "user"


class Team:
    """A project folder whose shared state lives in `<root>/.team/`."""

    def __init__(self, root: Path | str):
        self.root = Path(root).resolve()
        self.dir = self.root / ".team"

    def __repr__(self) -> str:
        return f"Team({str(self.root)!r})"

    def __eq__(self, other: object) -> bool:
        return isinstance(other, Team) and other.root == self.root

    def __hash__(self) -> int:
        return hash(self.root)

    @classmethod
    def resolve(cls, cwd: Path | str | None = None, env: Mapping[str, str] | None = None) -> "Team":
        """$HERMES_TEAM_DIR -> tmux @team_dir of my window -> nearest ancestor with .team/ -> cwd."""
        env = os.environ if env is None else env
        d = (env.get("HERMES_TEAM_DIR") or "").strip()
        if d:
            return cls(d)
        pane = my_pane()
        if pane:
            d = window_option(pane, "@team_dir")
            if d:
                return cls(d)
        here = Path(cwd or os.getcwd()).resolve()
        for p in (here, *here.parents):
            if (p / ".team").is_dir():
                return cls(p)
        return cls(here)

    # paths ---------------------------------------------------------
    def path(self, *parts: str) -> Path:
        return self.dir.joinpath(*parts)

    def exists(self) -> bool:
        return self.dir.is_dir()

    def ensure(self) -> "Team":
        """Create .team/ (with a .gitignore of `*` so it never lands in the user's repo)."""
        self.dir.mkdir(parents=True, exist_ok=True)
        gi = self.dir / ".gitignore"
        if not gi.exists():
            with contextlib.suppress(OSError):
                gi.write_text("*\n")
        return self

    @contextlib.contextmanager
    def lock(self, name: str) -> Iterator[None]:
        """Exclusive lock `.team/locks/<name>.lock`."""
        self.ensure()
        with store.flock(self.path("locks", f"{name}.lock")):
            yield

    # roles ---------------------------------------------------------
    def roles(self) -> list[str]:
        """Known teammate roles (spelling as spawned): agent state files, mailboxes, briefs, tmux panes."""
        names: dict[str, str] = {}

        def add(n: str) -> None:
            if valid_role(n) and n.lower() not in names:
                names[n.lower()] = n

        for sub, suffix in (("agents", ".json"), ("briefs", ".md")):
            d = self.path(sub)
            if d.is_dir():
                for f in sorted(d.iterdir()):
                    if f.name.endswith(suffix) and not f.name.startswith("."):
                        add(f.name[: -len(suffix)])
        d = self.path("mail")
        if d.is_dir():
            for f in sorted(d.iterdir()):
                if f.is_dir():
                    add(f.name)
        for r in self.tmux_roles():
            add(r)
        return [n for k, n in sorted(names.items()) if k not in ("user", SYSTEM)]

    def tmux_roles(self) -> list[str]:
        """@role of panes in tmux windows whose @team_dir is this team (best effort; [] without tmux)."""
        out = tmux("list-panes", "-a", "-F", "#{@team_dir}\t#{@role}")
        if not out:
            return []
        res = []
        for line in out.splitlines():
            d, _, r = line.partition("\t")
            if r and d and _same_dir(d, self.root):
                res.append(r)
        return res

    def canon_role(self, name: str) -> str | None:
        """Spelling of a known role matching `name` case-insensitively; 'lead' always exists."""
        if name.lower() == "lead":
            return "lead"
        for r in self.roles():
            if r.lower() == name.lower():
                return r
        return None


def _same_dir(a: str, b: Path) -> bool:
    try:
        return Path(a).resolve() == b
    except OSError:
        return False
